//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezultate
    {
        public int Id { get; set; }
        public int Clasa { get; set; }
        public string Nume { get; set; }
        public int P1 { get; set; }
        public int P2 { get; set; }
        public int P3 { get; set; }
        public string Prenume { get; set; }
        public string Scoala { get; set; }
    }
}
